### ISSUE TITLE
TransloaditAPI pod installation problems.

### ISSUE THREAD

**Issue by Asbat** [transloadit/ios-sdk#10]
There appears to be some problems with TransloaditAPI pod. It depends on AFNetworking's current version where AFHTTPClient is replaced with AFHTTPRequestOperationManager / AFHTTPSessionManager and TransloaditAPI still uses AFHTTPClient.

Installing the pod:
pod install
Analyzing dependencies
Downloading dependencies
Installing AFNetworking (2.5.1)
Installing Reachability (3.2)
Installing TransloaditAPI (0.1.6)
Generating Pods project
Integrating client project

...
NSURL *serviceUrl = [NSURL URLWithString:@"https://api2.transloadit.com/"];
AFHTTPClient *httpClient = [[AFHTTPClient alloc] initWithBaseURL:serviceUrl];  -> Use of undeclared identifier 'AFHTTPClient'
...

**Comment by MMasterson** [comment]
Sorry for the long wait @Asbat , I was just assigned to maintain the pod. I have fixed the issue - let me know if you have any other issues!
