### ISSUE TITLE
INVALID_AUTH_EXPIRES_PARAMETER error

### ISSUE THREAD

**Issue by VitalyTimofeev** [transloadit/ios-sdk#11]
A date formatter (https://github.com/transloadit/ios-sdk/blob/master/TransloaditLib/assembly/AssemblyBuilder.m#L82)
```objective-c
[dateFormatter setDateFormat:@"yyyy/MM/dd HH:mm:ss+00:00"];
```
may return 12-hour clock format string (see http://stackoverflow.com/a/7072285). So `expires` parameter will be `"expires": "2015/03/16 1:43:15 a.m.+00:00"` instead of expecting `"expires": "2015/03/16 1:43:15+00:00"`. This leads to INVALID_AUTH_EXPIRES_PARAMETER. It could be fixed by adding
```objective-c
[dateFormatter setLocale:[[NSLocale alloc] initWithLocaleIdentifier:@"en_US_POSIX"]];
```

**Comment by powtac** [comment]
+1

**Comment by kvz** [comment]
Would you be willing to send a pr for this?

**Comment by powtac** [comment]
Fix provided by @VitalyTimofeev !
