### ISSUE TITLE
When connecting to https, connection is lost every 5-6 seconds or so, but http works fine

### ISSUE THREAD

**Issue by kvz** [transloadit/ios-sdk#13]
This was reported by a Transloadit customer in our support tool, and I've asked them to provide more information in this ticket

**Comment by MMasterson** [comment]
@kvz any update on this? If it's iOS9 could be a easy switch.

**Comment by kvz** [comment]
Hey @MMasterson!

I just reopened that ticket with this response:

```
Hi Marc,

Might you have more information regarding this?
Our new iOS developer just mentioned in https://github.com/transloadit/ios-sdk/issues/13#issuecomment-231160057 that:

"If it's iOS9 could be a easy switch."

Also, we have upgraded our HTTPS stack recently which could also have improved the situation https://transloadit.com/blog/2016/07/ssl-upgraded/

Looking forward to hear from you!

​Kind regards,
```

**Comment by kvz** [comment]
Just got word that

> We ended up writing our own utility for iOS and no longer utilize Transloadit. Thanks for the followup!

So I'll close this issue until someone reports this again
