### ISSUE TITLE
NSError can't be passed

### ISSUE THREAD

**Issue by MMasterson** [transloadit/ios-sdk#16]
"I have one more doubt regarding how to read the error message in swift? I am not able to pass an NSError instance to the invokeAssembly(self.assembly, withError: nil) method, for now I am passing nil.
Can you please share a sample code or something so that I can read the error in case it occurs? "

From #14

**Comment by MMasterson** [comment]
@kpavankotesh how are you creating the NSError?

It should be something like this... (sorry for the lack of reference without your code)

`````Swift
var error: NSError?
var response : TransloaditResponse = invokeAssembly(self.assembly, withError: &error) 

if error != nil {
    //Error code
}
``````

Let me know if this helps!

**Comment by kpavankotesh** [comment]
I am using Swift version 2.2

When I use 
```
        var error: NSError?
        self.assembly.addFile(fileData, withError: &error)
```

the compiler gives me a fixable error -> ` '&' used with non-inout argument of type 'NSError!' ` and asks me to remove the '&' and subsequently throws the error  `Constant 'error' used before being initialized`

**Comment by kpavankotesh** [comment]
@MMasterson Hey any update on this? I got an error recently 

```
ERROR: DefaultHttpExecutor -- The request timed out.
ERROR: TransloaditRequest -- (null)
ERROR: Transloadit -- (null) -- Bored instance host is invalid using default path (null)
```

I would like to be able to recognize the errors and act accordingly/ show feedback to the user. Please let me know if there is any progress regarding this issue. Thaks

**Comment by apersaud** [comment]
This is fixed in their master branch. They just need to make a new official cocoapods release. You can point to the master branch for now:
```ruby
  pod 'TransloaditAPI', git: 'https://github.com/transloadit/ios-sdk.git'
```

**Comment by kvz** [comment]
We're close to deprecating this sdk in favor of https://github.com/transloadit/TransloaditKit/issues/1, feel free to weigh in there.

**Comment by MMasterson** [comment]
I've updated the Readme to reflect the change of the Pod repo and fix for this issue.
