### ISSUE TITLE
Is there any way to get the whole assembly status in the iOS SDK?

### ISSUE THREAD

**Issue by Amandeepsinghghai** [transloadit/ios-sdk#17]
-(TransloaditResponse*)deleteAssembly:(NSString*)assemblyID; 

The method expects an assemblyID, but I am not able to figure out where to get this from when the assembly upload is invoked(Using invoke assembly method) 

@MMasterson

**Comment by Amandeepsinghghai** [comment]
If I am able to get the assemblyID, I can update the status by pinging `https://api2.transloadit.com/assemblies/{assemblyID}`

**Comment by tim-kos** [comment]
That's right!

**Comment by Amandeepsinghghai** [comment]
@tim-kos I am not able to get the assemblyID from the iOS SDK. Could you guide me in this regard?
Not sure why this issue is closed?

**Comment by kpavankotesh** [comment]
@tim-kos Can you please tell us the procedure to get assembly ID on iOS end?

**Comment by tim-kos** [comment]
It should be in the response from the POST request to `api2.transloadit.com/assemblies`.

So something like this:

```
TransloaditResponse *response = [transloadit invokeAssembly:assembly withError:&error];
(NSString *)[[response getData] objectForKey:@"assembly_id"] 
```
