### ISSUE TITLE
Podspec is not published as latest version

### ISSUE THREAD

**Issue by brennanMKE** [transloadit/ios-sdk#7]
There appears to be another pod which is outdated showing up with the same name. I tried to force my Podfile to point to this repo instead but it is missing the required json version of the podspec.

`pod 'TransloaditAPI', :git => 'https://github.com/transloadit/ios-sdk.git', :tag => '1.0.0'`

I get the following error.

````
[!] No podspec found for `TransloaditAPI` in ...GitHub/ProjectName/iOS/Pods/TransloaditAPI/TransloaditAPI.podspec.json
````

Using CocoaPods Trunk you should be able to either take ownership or be added as an owner of the current pod. That will make it much easier to use your current code base.

http://blog.cocoapods.org/CocoaPods-Trunk/

**Comment by iotize** [comment]
Great, thanks.

**Comment by MMasterson** [comment]
@iotize Fixed :+1: Sorry for the long wait! Enjoy! Let me know if you have any other issues!
